---
- name: "Start Kibana"
  systemd:
    name: kibana
    daemon_reload: yes
    enabled: yes
    state: started

- name: "Restart Kibana"
  systemd:
    name: kibana
    daemon_reload: yes
    state: restarted
